---
- name: Test connectivity
  hosts: windows
  gather_facts: false
  vars: {}
  tasks:
    # - name: Ping!
    #   ansible.windows.win_ping:

    - name: Gather services running under domain user
      ansible.windows.win_service_info:
      register: all_svc_info

    - name: Filter services
      ansible.builtin.set_fact:
        all_svc_info: "{{ filtered_services }}"
        custom_services_list: "{{ filtered_and_mapped_services | sort(attribute='StartName') }}"
      vars:
        # This block now filters and maps the data in a single loop
        filtered_and_mapped_services: >-
          {%- set results = [] -%}
          {%- for service in all_svc_info.services -%}
            {%- if service.username
                and service.username | lower != 'localsystem'
                and not (service.username | lower).startswith('nt authority') -%}
              {%- set _ = results.append({
                  'SystemName': inventory_hostname,
                  'Name': service.name,
                  'Caption': service.display_name,
                  'StartMode': service.start_mode,
                  'StartName': service.username,
                  'State': service.state
                }) -%}
            {%- endif -%}
          {%- endfor -%}
          {{ results }}
        filtered_services: >-
          {%- set open_results = [] -%}
          {%- for service in all_svc_info.services -%}
            {%- if service.username
                and not (service.username | lower == 'localsystem')
                and (service.username | lower).startswith('nt authority') -%}
              {%- set _ = open_results.append(service) -%}
            {%- endif -%}
          {%- endfor -%}
          {{ open_results }}

    - ansible.builtin.debug:
        msg: '{{ all_svc_info }}'
