---
- name: Retrieve from Vault
  ansible.builtin.uri:
    url: "{{vault_addr}}/v1/ldap/{{principal.domain | lower}}/static-cred/{{principal.username | lower}}"
    method: GET
    return_content: true
    headers:
      "X-Vault-Token": '{{vault_token}}'
  register: target_account_resp

- name: Set facts
  ansible.builtin.set_fact:
    target_account_username: "{{target_account_resp.json.data.username}}"
    target_account_password: "{{target_account_resp.json.data.password}}"

